pragma Singleton
import QtQuick 2.15

Item {
    readonly property string fontFamily: "Font Awesome 6 Free"

    // Core icons
    readonly property string search: "\uf002"
    readonly property string folder: "\uf07b"
    readonly property string folderOpen: "\uf07c"
    readonly property string cube: "\uf1b2"
    readonly property string cubes: "\uf1b3"
    readonly property string box: "\uf466"
    readonly property string bolt: "\uf0e7"
    readonly property string gear: "\uf013"
    readonly property string cog: "\uf013"
    readonly property string sync: "\uf021"
    readonly property string rotate: "\uf021"
    readonly property string download: "\uf019"
    readonly property string image: "\uf03e"
    readonly property string images: "\uf302"
    readonly property string camera: "\uf030"
    readonly property string trash: "\uf1f8"
    readonly property string check: "\uf00c"
    readonly property string checkCircle: "\uf058"
    readonly property string times: "\uf00d"
    readonly property string timesCircle: "\uf057"
    readonly property string infoCircle: "\uf05a"
    readonly property string exclamationTriangle: "\uf071"
    readonly property string externalLink: "\uf08e"
    readonly property string link: "\uf0c1"
    readonly property string rss: "\uf09e"
    readonly property string filter: "\uf0b0"
    readonly property string chevronRight: "\uf054"
    readonly property string chevronLeft: "\uf053"
    readonly property string chevronDown: "\uf078"
    readonly property string arrowRight: "\uf061"
    readonly property string arrowLeft: "\uf060"
    readonly property string server: "\uf233"
    readonly property string database: "\uf1c0"
    readonly property string hdd: "\uf0a0"
    readonly property string clock: "\uf017"
    readonly property string eye: "\uf06e"
    readonly property string terminal: "\uf120"
    readonly property string tag: "\uf02b"
    readonly property string tags: "\uf02c"
    readonly property string layerGroup: "\uf5fd"
    readonly property string list: "\uf03a"
    readonly property string sliders: "\uf1de"
    readonly property string globe: "\uf0ac"
    readonly property string compass: "\uf14e"
    readonly property string copy: "\uf0c5"
    readonly property string share: "\uf064"
    readonly property string thLarge: "\uf009"
    readonly property string bars: "\uf0c9"
    readonly property string upload: "\uf093"
    readonly property string fileImport: "\uf56f"
    readonly property string fileExport: "\uf56e"
    readonly property string boxArchive: "\uf187"
    readonly property string stop: "\uf04d"
    readonly property string squareCheck: "\uf14a"
    readonly property string pause: "\uf04c"
    readonly property string play: "\uf04b"
    readonly property string arrowUp: "\uf062"
    readonly property string listOl: "\uf0cb"
}
